export const portfolio = {
  name: "Danielle Bryan Dizon",
  position: "Software Engineer",
  summary:
    "A highly dedicated software developer with years of experience in front-end technologies. Proficient in React and TypeScript, delivering robust and scalable web solutions. Recognized for significantly enhancing operational efficiency and user engagement through innovative and effective programming practices.",
  experience: [
    {
      company: "Accenture Philippines",
      companyLink: "https://www.accenture.com/ph-en",
      position: "Senior Software Engineer",
      description: [
        "Developed front-end solutions with ReactJS, TypeScript, and NodeJS to improve performance, scalability, and code quality.",
        "Conducted peer code reviews to ensure adherence to client’s coding standards and best practices.",
        "Engaged with product stakeholders by presenting functions and features and facilitate feedback that enhanced solution quality and usability.",
      ],
      years: "2023 - 2024",
      skills: [
        "ReactJS",
        "TypeScript",
        "NodeJS",
        "Jest",
        "Storybook",
        "Restful API",
        "Agile Development",
      ],
    },
    {
      company: "BCS Technology International – Philippines",
      companyLink: "https://bcstechnology.com.au/",
      position: "Junior Software Engineer",
      description: [
        "Built and optimized front-end features for healthcare applications using ReactJS and TypeScript.",
        "Collaborated with back-end developers to enhance performance and scalability of core features built with NodeJS and REST APIs that improves system reliability and response times.",
      ],
      years: "2021 - 2023",
      skills: [
        "ReactJS",
        "TypeScript",
        "NodeJS",
        "RESTful API",
        "MongoDB",
        "Agile Development",
      ],
    },
    {
      company: "RealPage Inc.",
      companyLink: "https://www.realpage.com/",
      position: "Junior Software Engineer",
      description: [
        "Collaborated with UI/UX designers and senior front-end developers to design and deliver high-quality real estate landing pages.",
        "Built and maintained real estate websites for U.S. clients using JavaScript, jQuery, and Kentico CMS that ensures responsiveness and cross-browser compatibility.",
      ],
      years: "2020 - 2021",
      skills: ["JavaScript", "Kentico CMS", "Agile Development"],
    },
    {
      company: "ADEC Innovations",
      companyLink: "https://www.adec-innovations.com/",
      position: "Systems Developer",
      description: [
        "Developed functions and features using JavaScript and OutSystems to measure and monitor carbon emissions and cleanliness across regions in the Philippines and internationally.",
        "Collaborated with product owners to demonstrate product features and gather their feedback to deliver more polished solutions.",
      ],
      years: "2018 - 2020",
      skills: ["Outsystems", "JavaScript", "JQuery", "Agile Development"],
    },
    {
      company: "China Banking Corporation",
      companyLink: "https://www.chinabank.ph/",
      position: "Systems Analysts",
      description: [
        "Provided application support and developed core functions, features, and code enhancements using JavaScript, C#, ASP.NET, and Entity Framework for in-house systems.",
        "Partnered with product owners to analyze and document core product functions and features to improve requirement clarity",
      ],
      years: "2017 - 2018",
      skills: [
        "C#",
        "Entity Framework",
        "JavaScript",
        "JQuery",
        "Waterfall Development",
      ],
    },
  ],
  education: [
    {
      name: "De La Salle - College of Saint Benilde",
      course: "BS - Information System",
      school_link: "https://www.benilde.edu.ph/",
      years: "2013 - 2017",
      course_link:
        "https://www.benilde.edu.ph/undergraduate-information-systems/",
    },
  ],
  projects: [
    {
      name: "bryanpascuadizon",
      description: "My Developer Portfolio",
      image: ["/images/projects/portfolio/portfolio-1.png"],
      website: "https://bryanpascuadizon.vercel.app/",
      github: "https://github.com/bryanpascuadizon/port-developer-portfolio",
      repositoryName: "port-developer-portfolio.git",
      skills: ["ReactJS", "Tailwind", "shadcn/ui"],
    },
    {
      name: "Freshpicks E-Commerce",
      description:
        "A simple e-commerce platform that sells fresh, high-quality microgreens, providing customers with a convenient way to enhance their health and meals.",
      image: [
        "/images/projects/freshpicks/freshpicks-1.png",
        "/images/projects/freshpicks/freshpicks-2.png",
        "/images/projects/freshpicks/freshpicks-3.png",
        "/images/projects/freshpicks/freshpicks-4.png",
        "/images/projects/freshpicks/freshpicks-5.png",
        "/images/projects/freshpicks/freshpicks-6.png",
        "/images/projects/freshpicks/freshpicks-7.png",
        "/images/projects/freshpicks/freshpicks-8.png",
        "/images/projects/freshpicks/freshpicks-9.png",
      ],
      website: "https://freshpicks.vercel.app/sign-in",
      github: "https://github.com/bryanpascuadizon/port-freshpicks-ecommerce",
      repositoryName: "port-freshpicks-ecommerce.git",
      skills: [
        "NextJS",
        "TypeScript",
        "Tailwind",
        "shadcn/ui",
        "React Query",
        "RestfulAPI",
        "Prisma",
      ],
    },
    {
      name: "DailyPeso",
      description:
        "DailyPeso is your simple, everyday money tracker that makes managing your finances feel easy.",
      image: [
        "/images/projects/dailypeso/dailypeso-1.png",
        "/images/projects/dailypeso/dailypeso-2.png",
        "/images/projects/dailypeso/dailypeso-3.png",
        "/images/projects/dailypeso/dailypeso-4.png",
        "/images/projects/dailypeso/dailypeso-5.png",
      ],
      website: "https://dailypeso.vercel.app/",
      github:
        "https://github.com/bryanpascuadizon/port-dailypeso-expense-tracker",
      repositoryName: "port-dailypeso-expense-tracker.git",
      skills: [
        "NextJS",
        "TypeScript",
        "Tailwind",
        "shadcn/ui",
        "React Query",
        "ExcelJS",
        "RestfulAPI",
        "Prisma",
      ],
    },
  ],
};
